# Generated by Django 3.2.25 on 2024-06-03 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20240603_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='docfile',
            new_name='docimage',
        ),
    ]
