# Generated by Django 3.2.25 on 2024-06-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rename_docfile_cars_docimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='docimage',
        ),
        migrations.AddField(
            model_name='cars',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo'),
        ),
    ]
