# Generated by Django 3.2.25 on 2024-06-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20240604_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo'),
        ),
    ]
