# Generated by Django 3.2.25 on 2024-06-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_cars_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photo'),
        ),
    ]
